# Generated by Django 2.1.7 on 2019-02-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190218_0632'),
        ('events', '0003_auto_20190218_0734'),
    ]

    operations = [
    ]
